### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by ever4cyth** [dmnfarrell/epitopepredict#1]
from mhcpredict import base,genome,analysis

is genome.py not included in the package?

Thanks!

**Comment by dmnfarrell** [comment]
The import was written wrong. It should be 

```
from mhcpredict import base,sequtils,analysis
```

You might find a few more bugs. I will add a few unit tests to check basic things are working.

**Comment by ever4cyth** [comment]
Thnaks for your reply, Damien!

What is this line about? Appreciate if you can show me how to get the data.

#get data
df = Genome.genbank2Dataframe(genbankfile, cds=True)

**Comment by dmnfarrell** [comment]
Yes the examples are probably a bit incomplete but I have updated them.
I have added some unit tests in tests.py and they can also serve as examples. You can run the tests from the package directory using `python tests.py`

The line `df = sequtils.genbank2Dataframe(genbankfile)` loads protiens from a genbank file into a dataframe format. You can also use fasta files with `df = sequtils.fasta2Dataframe(fastafile)`

There are sample files in the testing folder. genbank is more reliable than fasta because they use locus_tags for identifiers.

**Comment by ever4cyth** [comment]
thanks, works great now.
